### ISSUE TITLE
iptables support

### ISSUE THREAD

**Issue by deajan** [carlocorradini/node_exporter_installer#19]
Hi,

Just checked your node_exporter install script which looks great.
I don't get the iptables part.
Why do you allow connetions on port 9100 only from localhost ? Is there anything I misread ?

Also, it would be nice to have firewalld support for RHEL7-9, which would look like:
```
firewall-cmd --add-port=9100/tcp --permanent
firewall-cmd --reload
```

Best regards.

**Comment by carlocorradini** [comment]
@deajan Thanks 🥳
Maybe we could add an environment variable to set the correct "firewall" such as `INSTALL_NODE_EXPORTER_FIREWALL_TYPE` or automatically detect it like in `$INIT_SYSTEM`?

**Comment by carlocorradini** [comment]
For the localhost part, any suggestions?
Default to `127.0.0.1` and/or add env variable to add more?

**Comment by deajan** [comment]
> @deajan Thanks 🥳 Maybe we could add an environment variable to set the correct "firewall" such as `INSTALL_NODE_EXPORTER_FIREWALL_TYPE` or automatically detect it like in `$INIT_SYSTEM`?

I'd go for automatic detection since adding more and more env variables will end up making the script unnecessary complicated to execute.

I'd say:
```
setup_firewall() {
    if type firewall-cmd >/dev/null; then
        firewall-cmd --add-port=$NODE_EXPORTER_PORT/tcp --permanent
        firewall-cmd --reload
    elif type ufw > /dev/null; then
        ufw allow $NODE_EXPORTER_PORT/tcp
    # Must be executed after firewall-cmd and ufw test since they are mutually exclusive with iptables
    elif type iptables > /dev/null; then
        iptables -I INPUT 1 -p tcp --dport $NODE_EXPORTER_PORT -j ACCEPT
        iptables -I INPUT 3 -p tcp --dport $NODE_EXPORTER_PORT -j DROP
    else
        echo "No supported firewall found"
    fi
}



> For the localhost part, any suggestions? Default to `127.0.0.1` and/or add env variable to add more?

I don't see why the metrics should only be available to localhost since they should be read by the scraper which probably isn't local. Maybe the default should be open for any IP and you could add an optional environment variable which would restrict port 9100 to the specific IP of the scraper. What do you think ?
