### ISSUE TITLE
🚀 [REQUEST] - Support blackbox_exporter

### ISSUE THREAD

**Issue by deajan** [carlocorradini/node_exporter_installer#49]
### Summary

Since your script already has most of the necessary functions, it would be nice to support blackbox_exporter and possibly even snmp_exporter setup.

### Basic Example

something like `INSTALL_BLACKBOX_EXPORTER=true` env var ? Or even a `--setup-blackbox-exporter` option.

### Drawbacks

A bit more code, and a new option to install blackbox_exporter

**Comment by carlocorradini** [comment]
We can choose between three options:
1. Create two repo(s) that is similar to this but dedicated to `blackbox_exporter` and `snmp_exporter`
2. Rename this repo to `exporter_installer` with `3` scripts, one for each *_exporter.
3. Rename this repo to `exporter_installer` and modify the script to support the two new exporters increasing the number of options (multiple options, i.e. the version must be replicated three times)

**Comment by deajan** [comment]
The two first options create a new burden, being code duplication and more maintenance work IMO.

**Comment by carlocorradini** [comment]
Now that I'm thinking, I prefer the section option for the following reasons:
1. Mixing all the installers into a single one file is a burden to maintain. Moreover, by default: install all or you must select each one to install?
1. Create a common `__commons.sh` where all the common configuratons/functions are located. Then, for each installer source it via `. "./__commons.sh"`.
1. Create a new release whenever a script file is modified. This is very very useful also for backward compatibility.
1. Before release, the scripts are automatically inlined via [inline.sh](https://github.com/carlocorradini/inline) script.

PS: Currently, I don't have much time to add new installers script and modify the repo.

**Comment by deajan** [comment]
I've worked that path too in some of my scripts, having a "function collection" I'm carrying between scripts. The point is that your script becomes less portable, since you'll need to download two files.
I've resolved this by doing the following in my script, which downloads a copy of my function set and directly loads it into memory
```
function self_setup {
	echo "Setting up ofunctions"

	# Download copy of ofunctions.sh so we get Logger and ExecTasks functions
	source <(curl -L https://raw.githubusercontent.com/deajan/ofunctions/main/ofunctions.sh)
	# Don't polluate RUN_DIR since we won't need alerts
	_LOGGER_WRITE_PARTIAL_LOGS=false
}
```

Another solution I had was using a `merge.sh` script that replaces a placeholder with the actual code directly on github, see https://github.com/deajan/osync/blob/master/dev/merge.sh for an example.

PS: Just an idea, no hurry, I just happen to often install node_exporter and blackbox_exporter on the same machines

**Comment by carlocorradini** [comment]
Yup. The `inline.sh` (see https://github.com/carlocorradini/inline) script does exactly what you are describing. When developing, simply source common script. However, the final release script is inlined with commons.sh on top. Simpler: all three scripts will be the same at first because they are inlined with the common script.

PS: You can use `inline.sh` in your other scripts too. It is very very simple to use and it has additional features (e.g. recursion detection) built on top.

**Comment by deajan** [comment]
Exactly like my `ofunctions.sh` collection, except that my implementation has a lot of other functions that grew into it over the last 10 years or so, like parallel timed executions etc, and that I can select what part of ofunctions I want to inline via placeholders in my main script.

Anyway, I don't have more time myself to mod your script too... Sorry.
Guess this will remain a feat request for some time ;)
